// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHMe2mm3OM_qOrGJaq15-cnyCwQmCzV_g',
    appId: '1:1010772008094:web:632dbfe972f206f2e9af8f',
    messagingSenderId: '1010772008094',
    projectId: 'testapp-31832',
    authDomain: 'testapp-31832.firebaseapp.com',
    storageBucket: 'testapp-31832.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBREvjljjDrNzv4EPFl-z_bS9wtHNc0Osk',
    appId: '1:1010772008094:android:f196d7dda4dde207e9af8f',
    messagingSenderId: '1010772008094',
    projectId: 'testapp-31832',
    storageBucket: 'testapp-31832.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHMe2mm3OM_qOrGJaq15-cnyCwQmCzV_g',
    appId: '1:1010772008094:web:4612e45eb8f5d6dce9af8f',
    messagingSenderId: '1010772008094',
    projectId: 'testapp-31832',
    authDomain: 'testapp-31832.firebaseapp.com',
    storageBucket: 'testapp-31832.appspot.com',
  );
}
